dependencies:
    #-<organizacion/repo@version>
    - smartcontractkit/chainlink-brownie-contracts@0.4.1
compiler:
    solc:
        remappings:
            - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.4.1"

dotenv: .env
# set a custom mnemonic for the development network

billeteras:
    llave: ${PRIVATE_KEY}
